service: serverless-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1

functions:
  Users:
    handler: src/functions/users/get.handler
    events:
      - httpApi:
          path: /get
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
