service: serverless-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1

functions:
  addTodo:
    handler: src/functions/users/get.handler
    events:
      - httpApi:
          path: /get
          method: GET
  deleteTodo:
    handler: src/functions/users/delete.handler
    events:
      - httpApi:
          path: /delete/{id}
          method: DELETE
  updateTodo:
    handler: src/functions/users/update.handler
    events:
      - httpApi:
          path: /update/{id}
          method: PUT

plugins:
  - serverless-offline
  - serverless-plugin-typescript
