service: serverless-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1

functions:
  createTodo:
    handler: src/functions/users/create.createTodo
    events:
      - httpApi:
          path: /create
          method: POST
  getTodo:
    handler: src/functions/users/get.getTodo
    events:
      - httpApi:
          path: /get
          method: GET
  deleteTodo:
    handler: src/functions/users/delete.deleteTodo
    events:
      - httpApi:
          path: /delete/{id}
          method: DELETE
  updateTodo:
    handler: src/functions/users/update.updateTodo
    events:
      - httpApi:
          path: /update/{id}
          method: PUT

plugins:
  - serverless-offline
  - serverless-plugin-typescript
